export const CREATE_GAME_REQUESTED = 'CREATE_GAME_REQUESTED';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAILURE = 'CREATE_GAME_FAILURE';

export const RESET_GAME = 'RESET_GAME';

export const SPOTIFY_PROFILE_REQUESTED = 'SPOTIFY_PROFILE_REQUESTED';
export const SPOTIFY_PROFILE_SUCCESS = 'SPOTIFY_PROFILE_SUCCESS';
export const SPOTIFY_PROFILE_FAILURE = 'SPOTIFY_PROFILE_FAILURE';

export const PLAYLISTS_REQUESTED = 'PLAYLISTS_REQUESTED';
export const PLAYLISTS_SUCCESS = 'PLAYLISTS_SUCCESS';
export const PLAYLISTS_FAILURE = 'PLAYLISTS_FAILURE';


export const WS_GAME_CREATED = 'gameCreatedEvent';
export const WS_CREATE_GAME = 'create';
export const WS_JOIN_GAME = 'join';
export const WS_USER_JOINED_GAME = 'userJoinedGameEvent';
