// QUIZ
export const CREATE_QUIZ_REQUESTED = 'CREATE_QUIZ_REQUESTED';
export const CREATE_QUIZ_SUCCESS = 'CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILURE = 'CREATE_QUIZ_FAILURE';
export const RESET_QUIZ = 'RESET_QUIZ';

// SPOTIFY
export const SPOTIFY_PROFILE_REQUESTED = 'SPOTIFY_PROFILE_REQUESTED';
export const SPOTIFY_PROFILE_SUCCESS = 'SPOTIFY_PROFILE_SUCCESS';
export const SPOTIFY_PROFILE_FAILURE = 'SPOTIFY_PROFILE_FAILURE';
export const PLAYLISTS_REQUESTED = 'PLAYLISTS_REQUESTED';
export const PLAYLISTS_SUCCESS = 'PLAYLISTS_SUCCESS';
export const PLAYLISTS_FAILURE = 'PLAYLISTS_FAILURE';

// WEBSOCKETS
export const WS_GAME_CREATED = 'WS_GAME_CREATED';
export const WS_CREATE_GAME = 'WS_CREATE_GAME';
export const WS_GAME_STARTED = 'WS_GAME_STARTED';
export const WS_NEXT_QUESTION = 'WS_NEXT_QUESTION';
export const WS_NEXT_QUESTION_RESPONSE = 'WS_NEXT_QUESTION_RESPONSE';

export const WS_LAUNCH_GAME = 'WS_LAUNCH_GAME';
export const WS_START_GAME = 'WS_START_GAME';
export const WS_JOIN_GAME = 'WS_JOIN_GAME';
export const WS_USER_JOINED_GAME = 'WS_USER_JOINED_GAME';


export const WSO_START_GAME = 'WS_START_GAME';

export const GAME_TICK = 'GAME_TICK';

